server:
  port: 8080
spring:
  application:
    name: customer
  datasource:
    password: stockmarket
    url: jdbc:postgresql://localhost:5432/customer
    username: stockmarket
  jpa:
    hibernate:
      ddl-auto:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true